<a href="https://colab.research.google.com/github/tapatiroy2718/Blinkit/blob/main/Amazon_product_review_dataclean.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Details: Amazon products reviews dataset**</br>
about: it a synthetic Amazon_Data_Raw — 1,495 rows × 16 columns about the products

**Enviromental Setup**

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

**load the dataset**

In [ ]:
df = pd.read_excel("/Amazon_Products_Reviews_Dataset_UNCLEANED.xlsx")

display(df.head())

,product_id,product_name,category,Discounted_Price (INR),actual_price,discount_percentage,rating,Rating Count,about_product,user_id,user_name,review_id,review_title,review_content,IMG_LINK,product_link
0,B08SMJT55F,boAt Stone 250 Portable Wireless Speaker with ...,Electronics|HomeAudio|Speakers|BluetoothSpeakers,"₹1,199","₹3,990",70%,4.2,"2,908",Power- Get ready to be enthralled by the 5W RM...,"AHL435VQHZZXB545DXGLIZSACFOQ,AG6OEN75DD6ADCNOY...","Devashish Gautam,Vishakha,Sunny Tanna,Dr.Suman...","RLXE2MCKLCYMB,R39DFUZXNDFQ4,R30U7W2G83AI48,R2X...","Strudy, Awesome connectivity........but bass i...",The LED light is vibrant with multiple form se...,https://m.media-amazon.com/images/I/51J45Dcgkt...,https://www.amazon.in/boAt-Stone-250-Playback-...
1,B07F6GXNPB,EUREKA FORBES EUROCLEAN PAPER VACUUM CLEANER D...,"Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cl...",₹253,₹500,49%,4.3,"2,664",Special Anti-Microbial(Biocide Treated) Paper ...,"AEAHCVLMYLKLICSIKCTUS54NVQ2A,AFRIWQJKFSDZKTRTU...","Lulzdrone,KRISH,Harsh Shah,Harsh,HaPa,Inderjee...","R2K8VZSTF6Y1UH,R30LKPXEPE0CZE,R2714DP5UNSOQ,R1...","Bigger size,Superb.,Vacuum Bag,Price is reason...",These are the biggest one their models use and...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Eureka-Forbes-Euroclean-...
2,B08TTRVWKY,MILTON Smart Egg Boiler 360-Watts (Transparent...,Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,"₹1,099","₹1,899",42%,4.3,"1,811",3 Boiling Modes - The advanced appliance from ...,"AH2NLR3ZG7SADP6RTRU5PDZUBKYQ,AEDHYDNNCKCAOWK4...","Tapan Dutta,Seerat Dar,Saravana Kumar K N,Prad...","R1SPFVN2778DYH,R2GUT54B310MIN,R2WBP8YTLS3OPJ,R...","Nice good,Easy to use,Good , however little co...","Like it,Awesome product 😊,Follow the instructi...",https://m.media-amazon.com/images/I/41yrqUum9E...,https://www.amazon.in/MILTON-Smart-Egg-Boiler-...
3,B01MQ2A86A,"Logitech M331 Silent Plus Wireless Mouse, 2.4G...",Computers&Accessories|Accessories&Peripherals|...,NaN,"₹1,645",21%,4.6,"12,375",Quieter Click: Logitech’s SilentTouch Technolo...,"AE6TTPY5R4YW3XHTPGX6CGHLMVGA,AG5CBSM4UJ7KPPFIQ...","Awesome Shopper,Suresh madaka,Amazon Customer,...","R17S7JVWFH1X6W,R1HINIS5AG6PXD,R3VZFLZVFVZ13G,R...","Good but the scroll is now damaged,Nice,Noisel...",- excellent piece of wireless mouse- reasonabl...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Logitech-Silent-Wireless...
4,B08GM5S4CQ,Havells Instanio 10 Litre Storage Water Heater...,NaN,"₹6,990","₹14,290",51%,4.4,"1,771",Suitable for high-rise buildings and pressure ...,"AGUM6DLWGQ2LOM4MCKXEXKBXHXCQ,AELFZZK6GYFN3YA6T...","Amazon Customer,Gaurav,khalil shaikh,Aman Seti...","R3N1KWPD82KCJH,RUP7RE9R1GMG7,R1EM1ELIZK4UQO,R1...",Good product but attention needed in packing a...,"For this price range product design, look, spe...",https://m.media-amazon.com/images/I/31-XtyZy0I...,https://www.amazon.in/Havells-Instanio-Storage...

**display the last 5 dataset**

In [ ]:
df.tail()

,product_id,product_name,category,Discounted_Price (INR),actual_price,discount_percentage,rating,Rating Count,about_product,user_id,user_name,review_id,review_title,review_content,IMG_LINK,product_link
1490,B0756K5DYZ,Prestige Iris 750 Watt Mixer Grinder with 3 St...,Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,"₹3,249","₹6,295",48%,3.9,"43,070",Motor Warranty: 2; Product Warranty: 2;|Operat...,"AENY7MQ3WUVPIJ5I5GPDPMC3NKPA,AGUCURUVW2ZY4B5WL...","Prabhat,Chandrika,Pramesh969,Prity,Amit Kumar,...","R4FRMNYYMSIBC,R3L7S5SH36JCUJ,R1YN1N7YNW7AIJ,RF...","Juicer is not effective,Ok good,Products quali...","Juicer is not effective,Ok good,https://m.medi...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Prestige-Iris-Grinder-St...
1491,B01LY9W8AF,"Cello Eliza Plastic Laundry Bag/Basket, 50 lit...",Home&Kitchen|HomeStorage&Organization|LaundryO...,₹998.06,"₹1,282",22%,4.2,"7,274","Material: Plastic, Color: Light Grey100% food ...","AFUIW75M2VCMJ2RAD5HFEUHXCRKA,AFWO26UIM72Q7ZPHS...","Amit Singh,RN,Madhuri,SHUKDEB P.,Mano,Harsha,m...","R3ORPP4CPI5V9S,R2M6DE07UL43TF,R37BE8EXG1TX8H,R...","Nice product,Ok,The lid could be more sturdier...",It's a good product for strong daily laundry c...,https://m.media-amazon.com/images/I/51CyJ9dUiW...,https://www.amazon.in/Plastic-Laundry-Basket-L...
1492,B091JF2TFD,Boult Audio BassBuds Oak in-Ear Wired Earphone...,"Electronics|Headphones,Earbuds&Accessories|Hea...",₹499,"₹1,299",62%,3.9,"1,173","In-line Controls: Answer/reject/ calls, play/p...","AHYZC7TAK75CSXYF2V57TT2XB3VA,AHVSVASRHLY4HII4C...","Kulasekaranslrk,Amazon Customer,Sampada,Rudrak...","R3BZHVNU56YYR,R3JMZ9FQ4EE6ZQ,RCREBFSXZQ9JF,R1L...","Does its job for the price,Not for music but c...",A peculiar product in the market. Good sound q...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Boult-Audio-BassBuds-Oak...
1493,B0B3JSWG81,NGI Store 2 Pieces Pet Hair Removers for Your ...,"Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cle...",₹199,₹999,80%,3.1,2,"Versatile, Protects Your Clothes: MoveCatcher ...",AFPKVN5KLHB4MHSYDS25Q5MIWWKQ,Kunal Sen,R18OKMWGX8SA0L,Useless,Does not work as advertised at all. The pieces...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Hair-Removers-Laundry-Re...
1494,B00PVT30YI,Kitchen Mart Stainless Steel South Indian Filt...,"Home&Kitchen|Kitchen&HomeAppliances|Coffee,Tea...",₹292,₹499,41%,4.1,"4,238",Material: Food Grade stainless steel; Make aut...,"AFUYYV4MJWXM6FKQL6BR44OK52GA,AE5N2V2V7NEXSAKNO...","Amazon Customer,meena polkam,Amazon Customer,N...","R2UUBE6SD6DQ9Y,RYT31I1KBXJ0V,R4JW61N9AEDHA,R2D...","Coffee Filter,Just go for it!,Happy with the p...",Coffee Filter is just the right size for a sma...,NaN,https://www.amazon.in/Kitchen-Stainless-Indian...

**find the column**

In [ ]:
df.columns

Index(['product_id', 'product_name', 'category', 'Discounted_Price (INR)',
       'actual_price', 'discount_percentage', 'rating', 'Rating Count',
       'about_product', 'user_id', 'user_name', 'review_id', 'review_title',
       'review_content', 'IMG_LINK ', 'product_link'],
      dtype='object')

**Data Types**

In [ ]:
df.dtypes

product_id                object
product_name              object
category                  object
Discounted_Price (INR)    object
actual_price              object
discount_percentage       object
rating                    object
Rating Count              object
about_product             object
user_id                   object
user_name                 object
review_id                 object
review_title              object
review_content            object
IMG_LINK                  object
product_link              object
dtype: object

**Data Information**

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1495 entries, 0 to 1494
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              1479 non-null   object
 1   product_name            1476 non-null   object
 2   category                1473 non-null   object
 3   Discounted_Price (INR)  1473 non-null   object
 4   actual_price            1473 non-null   object
 5   discount_percentage     1473 non-null   object
 6   rating                  1470 non-null   object
 7   Rating Count            1468 non-null   object
 8   about_product           1473 non-null   object
 9   user_id                 1487 non-null   object
 10  user_name               1486 non-null   object
 11  review_id               1487 non-null   object
 12  review_title            1481 non-null   object
 13  review_content          1483 non-null   object
 14  IMG_LINK                1476 non-null   object
 15  product_link            1476 non-null   object
dtypes: object(16)
memory usage: 187.0+ KB

**Column Names**

In [ ]:
df.columns

Index(['product_id', 'product_name', 'category', 'Discounted_Price (INR)',
       'actual_price', 'discount_percentage', 'rating', 'Rating Count',
       'about_product', 'user_id', 'user_name', 'review_id', 'review_title',
       'review_content', 'IMG_LINK ', 'product_link'],
      dtype='object')

**Check Missing Values**

In [ ]:
df.isnull().sum()

product_id                16
product_name              19
category                  22
Discounted_Price (INR)    22
actual_price              22
discount_percentage       22
rating                    25
Rating Count              27
about_product             22
user_id                    8
user_name                  9
review_id                  8
review_title              14
review_content            12
IMG_LINK                  19
product_link              19
dtype: int64

**Duplicate Rows**

In [ ]:
df.duplicated().sum()

np.int64(13)

WE HAVE 13 DUPLICATE ROWS

**Find unique values of all column**

In [ ]:
column = df.columns
for i in column:
  print(i)
  print(df[i].unique())
  print()

product_id
['B08SMJT55F' 'B07F6GXNPB' 'B08TTRVWKY' ... 'B091JF2TFD' 'B0B3JSWG81'
 'B00PVT30YI']

product_name
['boAt Stone 250 Portable Wireless Speaker with 5W RMS Immersive Audio, RGB LEDs, Up to 8HRS Playtime, IPX7 Water Resistance, Multi-Compatibility Modes(Black)'
 'EUREKA FORBES EUROCLEAN PAPER VACUUM CLEANER DUST BAGS FOR EXCEL, ACE, 300, JET MODELS - SET OF 10'
 'MILTON Smart Egg Boiler 360-Watts (Transparent and Silver Grey), Boil Up to 7 Eggs'
 ...
 'Boult Audio BassBuds Oak in-Ear Wired Earphones with 10mm Extra Bass Driver and HD Sound with mic(Brown)'
 'NGI Store 2 Pieces Pet Hair Removers for Your Laundry Catcher Lint Remover for Washing Machine Lint Remover Reusable Portable Silica Gel Clothes Washer Dryer Floating Ball'
 'Kitchen Mart Stainless Steel South Indian Filter Coffee Drip Maker, Madras Kappi, Drip Decotion Maker160ml (2 Cup)']

category
['Electronics|HomeAudio|Speakers|BluetoothSpeakers'
 ' Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cleaning&Ironing|Vacuums&FloorCare|VacuumAccessories|VacuumBags|HandheldBags'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|EggBoilers'
 'Computers&Accessories|Accessories&Peripherals|Keyboards,Mice&InputDevices|Mice'
 nan
 'Electronics|Mobiles&Accessories|MobileAccessories|Maintenance,Upkeep&Repairs|ScreenProtectors'
 'Electronics|Mobiles&Accessories|Smartphones&BasicMobiles|Smartphones'
 'Computers&Accessories|NetworkingDevices|NetworkAdapters|WirelessUSBAdapters'
 'Electronics|HomeTheater,TV&Video|Accessories|RemoteControls'
 'Computers&Accessories|Accessories&Peripherals|Keyboards,Mice&InputDevices|Keyboard&MiceAccessories|MousePads'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|VacuumSealers'
 'Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cleaning&Ironing|Irons,Steamers&Accessories|Irons|DryIrons'
 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables'
 'OfficeProducts|OfficePaperProducts|Paper|Stationery|Notebooks,WritingPads&Diaries|CompositionNotebooks'
 'computers&accessories|accessories&peripherals|cables&accessories|cables|usbcables'
 'Computers&Accessories|Accessories&Peripherals|Keyboards,Mice&InputDevices|GraphicTablets'
 'Electronics|WearableTechnology|SmartWatches'
 'Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cleaning&Ironing|Irons,Steamers&Accessories|LintShavers'
 'Computers&Accessories|Tablets'
 'Home&Kitchen|Heating,Cooling&AirQuality|AirPurifiers|HEPAAirPurifiers'
 'Computers&Accessories|NetworkingDevices|Repeaters&Extenders '
 'Electronics|Headphones,Earbuds&Accessories|Headphones|In-Ear'
 'Computers&Accessories|Accessories&Peripherals|LaptopAccessories|Lapdesks'
 'Computers&Accessories|Accessories&Peripherals|USBGadgets|Lamps'
 'Electronics|GeneralPurposeBatteries&BatteryChargers'
 ' Home&Kitchen|CraftMaterials|PaintingMaterials|Paints'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|JuicerMixerGrinders'
 'Electronics|Mobiles&Accessories|MobileAccessories|Décor'
 'Computers&Accessories|ExternalDevices&DataStorage|PenDrives'
 'Computers&Accessories|Accessories&Peripherals|Audio&VideoAccessories|PCMicrophones'
 'Computers&Accessories|Accessories&Peripherals|Keyboards,Mice&InputDevices|Keyboard&MouseSets'
 'HOME&KITCHEN|KITCHEN&HOMEAPPLIANCES|VACUUM,CLEANING&IRONING|IRONS,STEAMERS&ACCESSORIES|IRONS|DRYIRONS'
 'Home&Kitchen|Heating,Cooling&AirQuality|WaterHeaters&Geysers|ImmersionRods'
 'Electronics|Mobiles&Accessories|MobileAccessories|Chargers|AutomobileChargers'
 'Electronics|Cameras&Photography|Accessories|Batteries&Chargers|BatteryChargers'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|Kettles&HotWaterDispensers|ElectricKettles'
 'Computers&Accessories|NetworkingDevices|Routers'
 'Home&Kitchen|Heating,Cooling&AirQuality|Fans|CeilingFans'
 'Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cleaning&Ironing|Vacuums&FloorCare|Vacuums|CanisterVacuums'
 'OFFICEPRODUCTS|OFFICEPAPERPRODUCTS|PAPER|STATIONERY|PENS,PENCILS&WRITINGSUPPLIES|PENS&REFILLS|GELINKROLLERBALLPENS'
 'Electronics|Mobiles&Accessories|MobileAccessories|Chargers|WallChargers'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|HandBlenders'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|Pop-upToasters'
 'Electronics|HomeTheater,TV&Video|Televisions|StandardTelevisions'
 'Computers&Accessories|Accessories&Peripherals|LaptopAccessories|CameraPrivacyCovers'
 'Home&Kitchen|Kitchen&HomeAppliances|WaterPurifiers&Accessories|WaterPurifierAccessories'
 'Home&Kitchen|Heating,Cooling&AirQuality|WaterHeaters&Geysers|StorageWaterHeaters'
 'Electronics|Mobiles&Accessories|MobileAccessories|Chargers|AutomobileChargers '
 'Electronics|Mobiles&Accessories|MobileAccessories|Mounts|HandlebarMounts'
 'Electronics|Headphones,Earbuds&Accessories|Headphones|On-Ear'
 'Computers&Accessories|Accessories&Peripherals|TabletAccessories|ScreenProtectors'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|Kettles&HotWaterDispensers|Kettle&ToasterSets'
 'Computers&Accessories|Accessories&Peripherals|LaptopAccessories|NotebookComputerStands'
 'electronics|mobiles&accessories|smartphones&basicmobiles|smartphones'
 'Electronics|HomeTheater,TV&Video|Accessories|Cables|SpeakerCables'
 'Electronics|HomeTheater,TV&Video|Accessories|Cables|HDMICables'
 'Electronics|GeneralPurposeBatteries&BatteryChargers|DisposableBatteries'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|WaffleMakers&Irons'
 'OfficeProducts|OfficePaperProducts|Paper|Stationery|Pens,Pencils&WritingSupplies|Pens&Refills|RetractableBallpointPens'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|Rice&PastaCookers'
 'Electronics|HomeTheater,TV&Video|Televisions|SmartTelevisions'
 'COMPUTERS&ACCESSORIES|EXTERNALDEVICES&DATASTORAGE|EXTERNALHARDDISKS'
 'Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cleaning&Ironing|Vacuums&FloorCare|Vacuums|Wet-DryVacuums'
 'Computers&Accessories|ExternalDevices&DataStorage|ExternalHardDisks'
 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|CableConnectionProtectors'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|MixerGrinders'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|InductionCooktop'
 'Computers&Accessories|Accessories&Peripherals|UninterruptedPowerSupplies'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|MiniFoodProcessors&Choppers'
 'Home&Kitchen|Heating,Cooling&AirQuality|RoomHeaters|ElectricHeaters'
 'Home&Kitchen|Kitchen&HomeAppliances|Coffee,Tea&Espresso|MilkFrothers'
 'Home&Kitchen|Kitchen&HomeAppliances|Coffee,Tea&Espresso|DripCoffeeMachines'
 ' Computers&Accessories|Printers,Inks&Accessories|Inks,Toners&Cartridges|InkjetInkCartridges'
 'electronics|wearabletechnology|smartwatches'
 'Home&Kitchen|Heating,Cooling&AirQuality|WaterHeaters&Geysers|InstantWaterHeaters'
 'Electronics|Mobiles&Accessories|MobileAccessories|Mounts|Bedstand&DeskMounts'
 'Computers&Accessories|Accessories&Peripherals|PCGamingPeripherals|GamingKeyboards'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|DeepFatFryers|AirFryers'
 'OfficeProducts|OfficePaperProducts|Paper|Stationery|Notebooks,WritingPads&Diaries|WireboundNotebooks'
 'Electronics|Mobiles&Accessories|MobileAccessories|AutomobileAccessories|Cradles'
 'Electronics|Accessories|MemoryCards|MicroSD'
 'Home&Kitchen|Heating,Cooling&AirQuality|Fans|TableFans'
 'COMPUTERS&ACCESSORIES|ACCESSORIES&PERIPHERALS|KEYBOARDS,MICE&INPUTDEVICES|MICE'
 'Electronics|Mobiles&Accessories|MobileAccessories|Mounts|Shower&WallMounts'
 'Home&Kitchen|Kitchen&HomeAppliances|SewingMachines&Accessories|Sewing&EmbroideryMachines'
 'Electronics|HomeTheater,TV&Video|SatelliteEquipment|SatelliteReceivers'
 'Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cleaning&Ironing|Vacuums&FloorCare|Vacuums|HandheldVacuums'
 'Computers&Accessories|Accessories&Peripherals|Cabels&Accessories|Cabels|USBCabels'
 'Electronics|Mobiles&Accessories|MobileAccessories|Cables&Adapters|OTGAdapters'
 'home&kitchen|kitchen&homeappliances|smallkitchenappliances|kettles&hotwaterdispensers|kettle&toastersets'
 'Electronics|Mobiles&Accessories|MobileAccessories|Photo&VideoAccessories|SelfieSticks'
 'Home&Kitchen|HomeStorage&Organization|LaundryOrganization|LaundryBaskets'
 'Computers&Accessories|Printers,Inks&Accessories|Printers|InkjetPrinters'
 'Electronics|GeneralPurposeBatteries&BatteryChargers|RechargeableBatteries'
 'Home&Kitchen|Heating,Cooling&AirQuality|RoomHeaters|FanHeaters'
 'Car&Motorbike|CarAccessories|InteriorAccessories|AirPurifiers&Ionizers'
 'Electronics|HomeAudio|Accessories|Adapters'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|Mills&Grinders|WetGrinders'
 'Computers&Accessories|Printers,Inks&Accessories|Printers'
 'OfficeProducts|OfficeElectronics|Calculators|Financial&Business'
 'Computers&Accessories|NetworkingDevices|Repeaters&Extenders'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|HandMixers'
 'Electronics|Cameras&Photography|Accessories|PhotoStudio&Lighting|PhotoBackgroundAccessories|BackgroundSupports'
 'Toys&Games|Arts&Crafts|Drawing&PaintingSupplies|ColouringPens&Markers'
 'Home&Kitchen|Heating,Cooling&AirQuality|RoomHeaters|HeatConvectors'
 ' OfficeProducts|OfficePaperProducts|Paper|Stationery|Notebooks,WritingPads&Diaries|WireboundNotebooks'
 'Computers&Accessories|Accessories&Peripherals|LaptopAccessories|Bags&Sleeves|LaptopSleeves&Slipcases'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|OvenToasterGrills'
 'Home&Kitchen|Heating,Cooling&AirQuality|Fans|ExhaustFans'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|DigitalKitchenScales'
 'Computers&Accessories|Printers,Inks&Accessories|Inks,Toners&Cartridges|InkjetInkCartridges'
 'OfficeProducts|OfficePaperProducts|Paper|Copy&PrintingPaper|ColouredPaper'
 'Home&Kitchen|Kitchen&HomeAppliances|Coffee,Tea&Espresso|CoffeePresses'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|StandMixers'
 'Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cleaning&Ironing|Irons,Steamers&Accessories|Irons|SteamIrons'
 'Electronics|Mobiles&Accessories|MobileAccessories|Stands'
 'Computers&Accessories|Accessories&Peripherals|Audio&VideoAccessories|PCSpeakers'
 'Home&Kitchen|Kitchen&HomeAppliances|Coffee,Tea&Espresso|EspressoMachines'
 'Electronics|Mobiles&Accessories|Smartphones&BasicMobiles|BasicMobiles'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|Juicers|ColdPressJuicers'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|SandwichMakers'
 'Computers&Accessories|Accessories&Peripherals|USBHubs'
 'Electronics|HomeTheater,TV&Video|Accessories|TVMounts,Stands&Turntables|TVWall&CeilingMounts'
 'Electronics|Mobiles&Accessories|MobileAccessories|StylusPens'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|Juicers'
 'Electronics|Mobiles&Accessories|MobileAccessories|Chargers|PowerBanks'
 'Home&Kitchen|Kitchen&HomeAppliances|WaterPurifiers&Accessories|WaterFilters&Purifiers'
 'OfficeProducts|OfficePaperProducts|Paper|Stationery|Pens,Pencils&WritingSupplies|Pens&Refills|FountainPens'
 'Electronics|HomeTheater,TV&Video|Projectors'
 'Electronics|Headphones,Earbuds&Accessories|Adapters'
 'Computers&Accessories|Monitors'
 'Computers&Accessories|Accessories&Peripherals|HardDriveAccessories|Caddies'
 'Computers&Accessories|Components|InternalSolidStateDrives'
 ' Computers&Accessories|NetworkingDevices|Routers'
 ' Computers&Accessories|Accessories&Peripherals|LaptopAccessories|LaptopChargers&PowerSupplies'
 'Electronics|Cameras&Photography|VideoCameras'
 'Computers&Accessories|Accessories&Peripherals|PCGamingPeripherals|GamingMice'
 'Electronics|Headphones,Earbuds&Accessories|Headphones|Over-Ear'
 'electronics|mobiles&accessories|mobileaccessories|chargers|wallchargers'
 'Electronics|HomeTheater,TV&Video|Accessories|3DGlasses'
 'Home&Kitchen|Kitchen&HomeAppliances|Coffee,Tea&Espresso|CoffeeMakerAccessories|MeasuringSpoons'
 'OfficeProducts|OfficePaperProducts|Paper|Stationery|Pens,Pencils&WritingSupplies|Pens&Refills|BottledInk'
 'COMPUTERS&ACCESSORIES|EXTERNALDEVICES&DATASTORAGE|PENDRIVES'
 'ELECTRONICS|HOMETHEATER,TV&VIDEO|ACCESSORIES|CABLES|HDMICABLES'
 'Computers&Accessories|Accessories&Peripherals|Keyboards,Mice&InputDevices|Keyboards'
 'COMPUTERS&ACCESSORIES|ACCESSORIES&PERIPHERALS|CABLES&ACCESSORIES|CABLES|USBCABLES'
 'OfficeProducts|OfficePaperProducts|Paper|Stationery|Notebooks,WritingPads&Diaries'
 'MusicalInstruments|Microphones|Condenser'
 'Home&Kitchen|Heating,Cooling&AirQuality|RoomHeaters'
 ' Electronics|HomeTheater,TV&Video|Accessories|Cables|RCACables'
 'Computers&Accessories|Accessories&Peripherals|LaptopAccessories|LaptopChargers&PowerSupplies'
 'Electronics|Cameras&Photography|Flashes|Macro&RinglightFlashes'
 'HOME&KITCHEN|HEATING,COOLING&AIRQUALITY|WATERHEATERS&GEYSERS|INSTANTWATERHEATERS'
 'home&kitchen|homestorage&organization|laundryorganization|laundrybaskets'
 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|SATACables '
 'Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cleaning&Ironing|Vacuums&FloorCare|Vacuums|RoboticVacuums'
 'Home&Kitchen|CraftMaterials|Scrapbooking|Tape'
 'Electronics|PowerAccessories|SurgeProtectors'
 'Computers&Accessories|Accessories&Peripherals|HardDiskBags'
 'Computers&Accessories|NetworkingDevices|NetworkAdapters|BluetoothAdapters'
 'Computers&Accessories|NetworkingDevices|NetworkAdapters|PowerLANAdapters'
 'Home&Kitchen|Heating,Cooling&AirQuality|Parts&Accessories|FanParts&Accessories'
 'Home&Kitchen|Heating,Cooling&AirQuality|Humidifiers'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|SmallApplianceParts&Accessories|StandMixerAccessories'
 'Computers&Accessories|ExternalDevices&DataStorage|ExternalMemoryCardReaders'
 'COMPUTERS&ACCESSORIES|ACCESSORIES&PERIPHERALS|KEYBOARDS,MICE&INPUTDEVICES|KEYBOARDS'
 'Electronics|Mobiles&Accessories|MobileAccessories|Cases&Covers|BasicCases'
 'electronics|hometheater,tv&video|accessories|tvmounts,stands&turntables|tvwall&ceilingmounts'
 'Electronics|Headphones,Earbuds&Accessories|Cases'
 'Home&Kitchen|CraftMaterials|PaintingMaterials|Paints'
 'HomeImprovement|Electrical|CordManagement'
 'Electronics|Cameras&Photography|Accessories|Tripods&Monopods|Tabletop&TravelTripods'
 ' Electronics|HomeTheater,TV&Video|Accessories|Cables|HDMICables'
 'Computers&Accessories|Accessories&Peripherals|PCGamingPeripherals|Headsets'
 ' Computers&Accessories|Accessories&Peripherals|PCGamingPeripherals|Gamepads'
 'Electronics|HomeTheater,TV&Video|Accessories|Cables|RCACables'
 'Electronics|Accessories|MemoryCards|SecureDigitalCards'
 'Computers&Accessories|Printers,Inks&Accessories|Inks,Toners&Cartridges|InkjetInkRefills&Kits'
 'Computers&Accessories|Accessories&Peripherals|Adapters|USBtoUSBAdapters'
 'Electronics|HomeAudio|Speakers|OutdoorSpeakers '
 'Home&Kitchen|HomeStorage&Organization|LaundryOrganization|IroningAccessories|SprayBottles'
 'OfficeProducts|OfficePaperProducts|Paper|Stationery|Pens,Pencils&WritingSupplies|Pens&Refills|LiquidInkRollerballPens'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|YogurtMakers'
 'Home&Kitchen|Heating,Cooling&AirQuality|AirConditioners|Split-SystemAirConditioners'
 'Computers&Accessories|Accessories&Peripherals|PCGamingPeripherals|Gamepads'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|DigitalKitchenScales|DigitalScales'
 'ELECTRONICS|HEADPHONES,EARBUDS&ACCESSORIES|HEADPHONES|IN-EAR'
 ' Computers&Accessories|Accessories&Peripherals|Keyboards,Mice&InputDevices|GraphicTablets'
 'Home&Kitchen|Kitchen&HomeAppliances|WaterPurifiers&Accessories|WaterCartridges'
 'Electronics|HomeAudio|Speakers|MultimediaSpeakerSystems'
 'Home&Kitchen|CraftMaterials|PaintingMaterials'
 'Home&Kitchen|Heating,Cooling&AirQuality|Fans|PedestalFans'
 'Electronics|Mobiles&Accessories|MobileAccessories|Décor|PhoneCharms'
 'OfficeProducts|OfficeElectronics|Calculators|Basic'
 ' Electronics|Headphones,Earbuds&Accessories|Headphones|On-Ear'
 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables '
 'electronics|mobiles&accessories|mobileaccessories|automobileaccessories|cradles'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|Rice&PastaCookers '
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|RotiMakers'
 'Electronics|HomeTheater,TV&Video|Accessories|Cables|OpticalCables'
 'Computers&Accessories|Accessories&Peripherals|Audio&VideoAccessories|PCHeadsets'
 'Home&Kitchen|Heating,Cooling&AirQuality|RoomHeaters|HalogenHeaters'
 'Computers&Accessories|NetworkingDevices|DataCards&Dongles'
 'OfficeProducts|OfficeElectronics|Calculators|Scientific'
 'Electronics|Cameras&Photography|SecurityCameras|DomeCameras'
 'Computers&Accessories|Accessories&Peripherals|TabletAccessories|Stands'
 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|EthernetCables'
 'Home&Kitchen|HomeStorage&Organization|LaundryOrganization|LaundryBags'
 'Health&PersonalCare|HomeMedicalSupplies&Equipment|HealthMonitors|WeighingScales|DigitalBathroomScales'
 'Electronics|HomeAudio|Accessories|SpeakerAccessories|Mounts'
 'Computers&Accessories|Printers,Inks&Accessories|Inks,Toners&Cartridges|TonerCartridges'
 'Computers&Accessories|Accessories&Peripherals|TabletAccessories|Bags,Cases&Sleeves|Cases'
 ' Electronics|Mobiles&Accessories|MobileAccessories|Chargers|WallChargers'
 'OfficeProducts|OfficePaperProducts|Paper|Stationery|Pens,Pencils&WritingSupplies|Pens&Refills|StickBallpointPens'
 'Electronics|Cameras&Photography|Accessories|Cleaners|CleaningKits'
 'Electronics|HomeAudio|MediaStreamingDevices|StreamingClients'
 'ELECTRONICS|HOMETHEATER,TV&VIDEO|TELEVISIONS|SMARTTELEVISIONS'
 'Home&Kitchen|Kitchen&HomeAppliances|Coffee,Tea&Espresso|CoffeeGrinders|ElectricGrinders '
 'computers&accessories|networkingdevices'
 'OfficeProducts|OfficePaperProducts|Paper|Stationery|Notebooks,WritingPads&Diaries|Notepads&MemoBooks'
 'OfficeProducts|OfficePaperProducts|Paper|Stationery|Pens,Pencils&WritingSupplies|Pens&Refills|GelInkRollerballPens'
 'Electronics|HomeAudio|Speakers|OutdoorSpeakers'
 'Home&Kitchen|CraftMaterials|DrawingMaterials|DrawingMedia|Pens'
 ' Electronics|Mobiles&Accessories|Smartphones&BasicMobiles|Smartphones'
 'Electronics|HomeAudio|Speakers|SoundbarSpeakers'
 'Electronics|Mobiles&Accessories|MobileAccessories|Photo&VideoAccessories|Flashes&SelfieLights|SelfieLights'
 'Electronics|Cameras&Photography|Accessories|Film'
 'Computers&Accessories|Accessories&Peripherals|LaptopAccessories'
 'Electronics|HomeTheater,TV&Video|AVReceivers&Amplifiers'
 'Computers&Accessories|ExternalDevices&DataStorage|ExternalSolidStateDrives'
 ' Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables'
 'Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cleaning&Ironing|PressureWashers,Steam&WindowCleaners'
 'Electronics|Headphones,Earbuds&Accessories|Earpads'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|Juicers '
 'Computers&Accessories|Accessories&Peripherals|LaptopAccessories|CoolingPads'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|SmallApplianceParts&Accessories'
 'Computers&Accessories|Accessories&Peripherals|Audio&VideoAccessories|Webcams&VoIPEquipment|Webcams'
 'Computers&Accessories|Laptops|TraditionalLaptops'
 'Electronics|Cameras&Photography|Accessories|Tripods&Monopods|TripodLegs'
 'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances'
 'Electronics|Mobiles&Accessories|MobileAccessories|Photo&VideoAccessories|Tripods'
 'Home&Kitchen|CraftMaterials|DrawingMaterials|DrawingMedia|Pencils|WoodenPencils'
 'Electronics|Cameras&Photography|Accessories|Tripods&Monopods|CompleteTripodUnits'
 'Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cleaning&Ironing|Irons,Steamers&Accessories|Irons|DryIrons '
 'Computers&Accessories|Accessories&Peripherals|Keyboards,Mice&InputDevices|Keyboard&MiceAccessories|DustCovers'
 'Computers&Accessories|Accessories&Peripherals|USBGadgets|Lamps '
 'Computers&Accessories|Components|InternalHardDrives'

**Remove extra spaces from column names**

In [ ]:
df.columns = df.columns.str.strip()

1. product_id : Check duplicate values, remove extra spaces, ensure all Product
IDs are in the same format.
2. product_name : 30 missing values, remove extra spaces and convert to Proper Case.
3. category : 30 missing values, remove extra spaces and standardize category names.
4. Discounted_Price (INR) : Remove ₹, Rs., commas and spaces, convert data type to Float, all values should be > 0.
5. actual_price : Remove ₹ and commas, convert data type to Float, all values should be > 0 and greater than or equal to Discounted Price.
6. discount_percentage : Remove % symbol, convert data type to Float, all values should be > 0 and < 100.
7. rating : Missing values, convert data type to Float, rating should be between 1 and 5.
8. Rating Count : Remove commas, convert data type to Int, all values should be ≥ 0.
9. about_product : 30 missing values, remove extra spaces and unwanted special characters.
10. user_id : 30 missing values, ensure proper formatting and remove extra spaces.
11. user_name : 30 missing values, convert into Proper Case and remove extra spaces.
12. review_id : Check duplicate values and ensure all Review IDs are unique.
13. review_title : 30 missing values, remove extra spaces and unwanted symbols.
14. review_content : 30 missing values, clean unwanted spaces, special characters and blank text.
15. IMG_LINK : 30 missing values, ensure all links are valid and start with https://.
16. product_link : 30 missing values, ensure all links are valid and remove broken URLs.
17. Duplicate Records : Remove duplicate rows from the dataset.
18. Missing Values : Fill numeric columns with Median and categorical columns with Mode or "Unknown".
19. Data Type : Convert all price, rating, discount and rating count columns into appropriate numeric data types.

**Data cleaning**

**1. product_id**

step: remove "B0" from all value in product_id column

In [ ]:
df['product_id'] = df['product_id'].str.replace('B0','',regex=True)
display(df.head())

,product_id,product_name,category,Discounted_Price (INR),actual_price,discount_percentage,rating,Rating Count,about_product,user_id,user_name,review_id,review_title,review_content,IMG_LINK,product_link
0,8SMJT55F,boAt Stone 250 Portable Wireless Speaker with ...,Electronics|HomeAudio|Speakers|BluetoothSpeakers,"₹1,199","₹3,990",70%,4.2,"2,908",Power- Get ready to be enthralled by the 5W RM...,"AHL435VQHZZXB545DXGLIZSACFOQ,AG6OEN75DD6ADCNOY...","Devashish Gautam,Vishakha,Sunny Tanna,Dr.Suman...","RLXE2MCKLCYMB,R39DFUZXNDFQ4,R30U7W2G83AI48,R2X...","Strudy, Awesome connectivity........but bass i...",The LED light is vibrant with multiple form se...,https://m.media-amazon.com/images/I/51J45Dcgkt...,https://www.amazon.in/boAt-Stone-250-Playback-...
1,7F6GXNPB,EUREKA FORBES EUROCLEAN PAPER VACUUM CLEANER D...,"Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cl...",₹253,₹500,49%,4.3,"2,664",Special Anti-Microbial(Biocide Treated) Paper ...,"AEAHCVLMYLKLICSIKCTUS54NVQ2A,AFRIWQJKFSDZKTRTU...","Lulzdrone,KRISH,Harsh Shah,Harsh,HaPa,Inderjee...","R2K8VZSTF6Y1UH,R30LKPXEPE0CZE,R2714DP5UNSOQ,R1...","Bigger size,Superb.,Vacuum Bag,Price is reason...",These are the biggest one their models use and...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Eureka-Forbes-Euroclean-...
2,8TTRVWKY,MILTON Smart Egg Boiler 360-Watts (Transparent...,Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,"₹1,099","₹1,899",42%,4.3,"1,811",3 Boiling Modes - The advanced appliance from ...,"AH2NLR3ZG7SADP6RTRU5PDZUBKYQ,AEDHYDNNCKCAOWK4...","Tapan Dutta,Seerat Dar,Saravana Kumar K N,Prad...","R1SPFVN2778DYH,R2GUT54B310MIN,R2WBP8YTLS3OPJ,R...","Nice good,Easy to use,Good , however little co...","Like it,Awesome product 😊,Follow the instructi...",https://m.media-amazon.com/images/I/41yrqUum9E...,https://www.amazon.in/MILTON-Smart-Egg-Boiler-...
3,1MQ2A86A,"Logitech M331 Silent Plus Wireless Mouse, 2.4G...",Computers&Accessories|Accessories&Peripherals|...,NaN,"₹1,645",21%,4.6,"12,375",Quieter Click: Logitech’s SilentTouch Technolo...,"AE6TTPY5R4YW3XHTPGX6CGHLMVGA,AG5CBSM4UJ7KPPFIQ...","Awesome Shopper,Suresh madaka,Amazon Customer,...","R17S7JVWFH1X6W,R1HINIS5AG6PXD,R3VZFLZVFVZ13G,R...","Good but the scroll is now damaged,Nice,Noisel...",- excellent piece of wireless mouse- reasonabl...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Logitech-Silent-Wireless...
4,8GM5S4CQ,Havells Instanio 10 Litre Storage Water Heater...,NaN,"₹6,990","₹14,290",51%,4.4,"1,771",Suitable for high-rise buildings and pressure ...,"AGUM6DLWGQ2LOM4MCKXEXKBXHXCQ,AELFZZK6GYFN3YA6T...","Amazon Customer,Gaurav,khalil shaikh,Aman Seti...","R3N1KWPD82KCJH,RUP7RE9R1GMG7,R1EM1ELIZK4UQO,R1...",Good product but attention needed in packing a...,"For this price range product design, look, spe...",https://m.media-amazon.com/images/I/31-XtyZy0I...,https://www.amazon.in/Havells-Instanio-Storage...

**Remove extra spaces**

In [ ]:
df["product_id"] = df["product_id"].str.strip()

**Duplicate Product IDs**

In [ ]:
df["product_id"].duplicated().sum()

np.int64(146)

**2.Product Name**

**Fill missing values**

In [ ]:
df["product_name"] = df["product_name"].fillna("Unknown")

**Convert to Proper Case**

In [ ]:
df["product_name"] = df["product_name"].str.title()

**Remove extra spaces**

In [ ]:
df["product_id"] = df["product_id"].str.strip()

**Category**

Check missing values

In [ ]:
df["category"].isnull().sum()

np.int64(22)

Fill missing values

In [ ]:
df["category"] = df["category"].fillna("Unknown")

Remove extra spaces

In [ ]:
df["category"] = df["category"].str.strip()

**4.Discounted Price**

Remove ₹

In [ ]:
df["Discounted_Price (INR)"] = df["Discounted_Price (INR)"].str.replace("₹","",regex=False)

Remove Rs.

In [ ]:
df["Discounted_Price (INR)"] = df["Discounted_Price (INR)"].str.replace("Rs.","",regex=False)

Remove commas

In [ ]:
df["Discounted_Price (INR)"] = df["Discounted_Price (INR)"].str.replace(",","",regex=False)

Convert to Float

In [ ]:
df["Discounted_Price (INR)"] = pd.to_numeric(df["Discounted_Price (INR)"],errors="coerce")

Replace values less than or equal to 0

In [ ]:
df.loc[df["Discounted_Price (INR)"]<=0,"Discounted_Price (INR)"]=np.nan

Fill missing values

In [ ]:
df["Discounted_Price (INR)"]=df["Discounted_Price (INR)"].fillna(df["Discounted_Price (INR)"].median())

Show the table

In [ ]:
display(df.head())

,product_id,product_name,category,Discounted_Price (INR),actual_price,discount_percentage,rating,Rating Count,about_product,user_id,user_name,review_id,review_title,review_content,IMG_LINK,product_link
0,8SMJT55F,Boat Stone 250 Portable Wireless Speaker With ...,Electronics|HomeAudio|Speakers|BluetoothSpeakers,1199.0,3990.0,70%,4.2,"2,908",Power- Get ready to be enthralled by the 5W RM...,"AHL435VQHZZXB545DXGLIZSACFOQ,AG6OEN75DD6ADCNOY...","Devashish Gautam,Vishakha,Sunny Tanna,Dr.Suman...","RLXE2MCKLCYMB,R39DFUZXNDFQ4,R30U7W2G83AI48,R2X...","Strudy, Awesome connectivity........but bass i...",The LED light is vibrant with multiple form se...,https://m.media-amazon.com/images/I/51J45Dcgkt...,https://www.amazon.in/boAt-Stone-250-Playback-...
1,7F6GXNPB,Eureka Forbes Euroclean Paper Vacuum Cleaner D...,"Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cle...",253.0,500.0,49%,4.3,"2,664",Special Anti-Microbial(Biocide Treated) Paper ...,"AEAHCVLMYLKLICSIKCTUS54NVQ2A,AFRIWQJKFSDZKTRTU...","Lulzdrone,KRISH,Harsh Shah,Harsh,HaPa,Inderjee...","R2K8VZSTF6Y1UH,R30LKPXEPE0CZE,R2714DP5UNSOQ,R1...","Bigger size,Superb.,Vacuum Bag,Price is reason...",These are the biggest one their models use and...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Eureka-Forbes-Euroclean-...
2,8TTRVWKY,Milton Smart Egg Boiler 360-Watts (Transparent...,Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,1099.0,1899.0,42%,4.3,"1,811",3 Boiling Modes - The advanced appliance from ...,"AH2NLR3ZG7SADP6RTRU5PDZUBKYQ,AEDHYDNNCKCAOWK4...","Tapan Dutta,Seerat Dar,Saravana Kumar K N,Prad...","R1SPFVN2778DYH,R2GUT54B310MIN,R2WBP8YTLS3OPJ,R...","Nice good,Easy to use,Good , however little co...","Like it,Awesome product 😊,Follow the instructi...",https://m.media-amazon.com/images/I/41yrqUum9E...,https://www.amazon.in/MILTON-Smart-Egg-Boiler-...
3,1MQ2A86A,"Logitech M331 Silent Plus Wireless Mouse, 2.4G...",Computers&Accessories|Accessories&Peripherals|...,799.0,1645.0,21%,4.6,"12,375",Quieter Click: Logitech’s SilentTouch Technolo...,"AE6TTPY5R4YW3XHTPGX6CGHLMVGA,AG5CBSM4UJ7KPPFIQ...","Awesome Shopper,Suresh madaka,Amazon Customer,...","R17S7JVWFH1X6W,R1HINIS5AG6PXD,R3VZFLZVFVZ13G,R...","Good but the scroll is now damaged,Nice,Noisel...",- excellent piece of wireless mouse- reasonabl...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Logitech-Silent-Wireless...
4,8GM5S4CQ,Havells Instanio 10 Litre Storage Water Heater...,Unknown,6990.0,14290.0,51%,4.4,"1,771",Suitable for high-rise buildings and pressure ...,"AGUM6DLWGQ2LOM4MCKXEXKBXHXCQ,AELFZZK6GYFN3YA6T...","Amazon Customer,Gaurav,khalil shaikh,Aman Seti...","R3N1KWPD82KCJH,RUP7RE9R1GMG7,R1EM1ELIZK4UQO,R1...",Good product but attention needed in packing a...,"For this price range product design, look, spe...",https://m.media-amazon.com/images/I/31-XtyZy0I...,https://www.amazon.in/Havells-Instanio-Storage...

**Actual Price**

Remove ₹

In [ ]:
df["actual_price"]=df["actual_price"].str.replace("₹","",regex=False)

Remove commas

In [ ]:
df["actual_price"]=df["actual_price"].str.replace(",","",regex=False)

Convert to Float

In [ ]:
df["actual_price"]=pd.to_numeric(df["actual_price"],errors="coerce")

Replace values less than or equal to 0

In [ ]:
df.loc[df["actual_price"]<=0,"actual_price"]=np.nan

Fill missing values

In [ ]:
df["actual_price"]=df["actual_price"].fillna(df["actual_price"].median())

**Discount Percentage**

Remove %

In [ ]:
df["discount_percentage"]=df["discount_percentage"].str.replace("%","",regex=False)

Convert to Float

In [ ]:
df["discount_percentage"]=pd.to_numeric(df["discount_percentage"],errors="coerce")

Replace values outside 0-100

In [ ]:
df.loc[(df["discount_percentage"]<0)|(df["discount_percentage"]>100),"discount_percentage"]=np.nan

Fill missing values

In [ ]:
df["discount_percentage"]=df["discount_percentage"].fillna(df["discount_percentage"].median())

**Rating**

Convert to Float

In [ ]:
df["rating"]=pd.to_numeric(df["rating"],errors="coerce")

Replace ratings outside 1-5

In [ ]:
df.loc[(df["rating"]<1)|(df["rating"]>5),"rating"]=np.nan

Fill missing ratings

In [ ]:
df["rating"]=df["rating"].fillna(df["rating"].median())

**Rating Count**

Remove commas

In [ ]:
df["Rating Count"]=df["Rating Count"].astype(str).str.replace(",","",regex=False)

Convert to Integer

In [ ]:
df["Rating Count"]=pd.to_numeric(df["Rating Count"],errors="coerce")

Fill missing values

In [ ]:
df["Rating Count"]=df["Rating Count"].fillna(df["Rating Count"].median())

**About Product**

Fill missing values

In [ ]:
df["about_product"]=df["about_product"].fillna("Unknown")

**User ID**

Fill missing values

In [ ]:
df["user_id"]=df["user_id"].fillna("Unknown")

**User Name**

Fill missing values

In [ ]:
df["user_name"]=df["user_name"].fillna("Unknown")

Convert to Proper Case

In [ ]:
df["user_name"]=df["user_name"].str.title()

**Review Title**

Fill missing values

In [ ]:
df["review_title"]=df["review_title"].fillna("No Review")

**Review Content**

Fill missing values

In [ ]:
df["review_content"]=df["review_content"].fillna("No Review")

**Image Link**

Fill missing values

In [ ]:
df["IMG_LINK"]=df["IMG_LINK"].fillna("No Image")

**Product Link**

Fill missing values

In [ ]:
df["product_link"]=df["product_link"].fillna("No Link")

Show the Table

In [ ]:

display(df.head())

,product_id,product_name,category,Discounted_Price (INR),actual_price,discount_percentage,rating,Rating Count,about_product,user_id,user_name,review_id,review_title,review_content,IMG_LINK,product_link
0,8SMJT55F,Boat Stone 250 Portable Wireless Speaker With ...,Electronics|HomeAudio|Speakers|BluetoothSpeakers,1199.0,3990.0,70.0,4.2,2908.0,Power- Get ready to be enthralled by the 5W RM...,"AHL435VQHZZXB545DXGLIZSACFOQ,AG6OEN75DD6ADCNOY...","Devashish Gautam,Vishakha,Sunny Tanna,Dr.Suman...","RLXE2MCKLCYMB,R39DFUZXNDFQ4,R30U7W2G83AI48,R2X...","Strudy, Awesome connectivity........but bass i...",The LED light is vibrant with multiple form se...,https://m.media-amazon.com/images/I/51J45Dcgkt...,https://www.amazon.in/boAt-Stone-250-Playback-...
1,7F6GXNPB,Eureka Forbes Euroclean Paper Vacuum Cleaner D...,"Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cle...",253.0,500.0,49.0,4.3,2664.0,Special Anti-Microbial(Biocide Treated) Paper ...,"AEAHCVLMYLKLICSIKCTUS54NVQ2A,AFRIWQJKFSDZKTRTU...","Lulzdrone,Krish,Harsh Shah,Harsh,Hapa,Inderjee...","R2K8VZSTF6Y1UH,R30LKPXEPE0CZE,R2714DP5UNSOQ,R1...","Bigger size,Superb.,Vacuum Bag,Price is reason...",These are the biggest one their models use and...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Eureka-Forbes-Euroclean-...
2,8TTRVWKY,Milton Smart Egg Boiler 360-Watts (Transparent...,Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,1099.0,1899.0,42.0,4.3,1811.0,3 Boiling Modes - The advanced appliance from ...,"AH2NLR3ZG7SADP6RTRU5PDZUBKYQ,AEDHYDNNCKCAOWK4...","Tapan Dutta,Seerat Dar,Saravana Kumar K N,Prad...","R1SPFVN2778DYH,R2GUT54B310MIN,R2WBP8YTLS3OPJ,R...","Nice good,Easy to use,Good , however little co...","Like it,Awesome product 😊,Follow the instructi...",https://m.media-amazon.com/images/I/41yrqUum9E...,https://www.amazon.in/MILTON-Smart-Egg-Boiler-...
3,1MQ2A86A,"Logitech M331 Silent Plus Wireless Mouse, 2.4G...",Computers&Accessories|Accessories&Peripherals|...,799.0,1645.0,21.0,4.6,12375.0,Quieter Click: Logitech’s SilentTouch Technolo...,"AE6TTPY5R4YW3XHTPGX6CGHLMVGA,AG5CBSM4UJ7KPPFIQ...","Awesome Shopper,Suresh Madaka,Amazon Customer,...","R17S7JVWFH1X6W,R1HINIS5AG6PXD,R3VZFLZVFVZ13G,R...","Good but the scroll is now damaged,Nice,Noisel...",- excellent piece of wireless mouse- reasonabl...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Logitech-Silent-Wireless...
4,8GM5S4CQ,Havells Instanio 10 Litre Storage Water Heater...,Unknown,6990.0,14290.0,51.0,4.4,1771.0,Suitable for high-rise buildings and pressure ...,"AGUM6DLWGQ2LOM4MCKXEXKBXHXCQ,AELFZZK6GYFN3YA6T...","Amazon Customer,Gaurav,Khalil Shaikh,Aman Seti...","R3N1KWPD82KCJH,RUP7RE9R1GMG7,R1EM1ELIZK4UQO,R1...",Good product but attention needed in packing a...,"For this price range product design, look, spe...",https://m.media-amazon.com/images/I/31-XtyZy0I...,https://www.amazon.in/Havells-Instanio-Storage...

In [ ]:

display(df.tail())

,product_id,product_name,category,Discounted_Price (INR),actual_price,discount_percentage,rating,Rating Count,about_product,user_id,user_name,review_id,review_title,review_content,IMG_LINK,product_link
1490,756K5DYZ,Prestige Iris 750 Watt Mixer Grinder With 3 St...,Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,3249.00,6295.0,48.0,3.9,43070.0,Motor Warranty: 2; Product Warranty: 2;|Operat...,"AENY7MQ3WUVPIJ5I5GPDPMC3NKPA,AGUCURUVW2ZY4B5WL...","Prabhat,Chandrika,Pramesh969,Prity,Amit Kumar,...","R4FRMNYYMSIBC,R3L7S5SH36JCUJ,R1YN1N7YNW7AIJ,RF...","Juicer is not effective,Ok good,Products quali...","Juicer is not effective,Ok good,https://m.medi...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Prestige-Iris-Grinder-St...
1491,1LY9W8AF,"Cello Eliza Plastic Laundry Bag/Basket, 50 Lit...",Home&Kitchen|HomeStorage&Organization|LaundryO...,998.06,1282.0,22.0,4.2,7274.0,"Material: Plastic, Color: Light Grey100% food ...","AFUIW75M2VCMJ2RAD5HFEUHXCRKA,AFWO26UIM72Q7ZPHS...","Amit Singh,Rn,Madhuri,Shukdeb P.,Mano,Harsha,M...","R3ORPP4CPI5V9S,R2M6DE07UL43TF,R37BE8EXG1TX8H,R...","Nice product,Ok,The lid could be more sturdier...",It's a good product for strong daily laundry c...,https://m.media-amazon.com/images/I/51CyJ9dUiW...,https://www.amazon.in/Plastic-Laundry-Basket-L...
1492,91JF2TFD,Boult Audio Bassbuds Oak In-Ear Wired Earphone...,"Electronics|Headphones,Earbuds&Accessories|Hea...",499.00,1299.0,62.0,3.9,1173.0,"In-line Controls: Answer/reject/ calls, play/p...","AHYZC7TAK75CSXYF2V57TT2XB3VA,AHVSVASRHLY4HII4C...","Kulasekaranslrk,Amazon Customer,Sampada,Rudrak...","R3BZHVNU56YYR,R3JMZ9FQ4EE6ZQ,RCREBFSXZQ9JF,R1L...","Does its job for the price,Not for music but c...",A peculiar product in the market. Good sound q...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Boult-Audio-BassBuds-Oak...
1493,B3JSWG81,Ngi Store 2 Pieces Pet Hair Removers For Your ...,"Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cle...",199.00,999.0,80.0,3.1,2.0,"Versatile, Protects Your Clothes: MoveCatcher ...",AFPKVN5KLHB4MHSYDS25Q5MIWWKQ,Kunal Sen,R18OKMWGX8SA0L,Useless,Does not work as advertised at all. The pieces...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Hair-Removers-Laundry-Re...
1494,0PVT30YI,Kitchen Mart Stainless Steel South Indian Filt...,"Home&Kitchen|Kitchen&HomeAppliances|Coffee,Tea...",292.00,499.0,41.0,4.1,4238.0,Material: Food Grade stainless steel; Make aut...,"AFUYYV4MJWXM6FKQL6BR44OK52GA,AE5N2V2V7NEXSAKNO...","Amazon Customer,Meena Polkam,Amazon Customer,N...","R2UUBE6SD6DQ9Y,RYT31I1KBXJ0V,R4JW61N9AEDHA,R2D...","Coffee Filter,Just go for it!,Happy with the p...",Coffee Filter is just the right size for a sma...,No Image,https://www.amazon.in/Kitchen-Stainless-Indian...